POST http://127.0.0.1:18968/waitResponse?name=test
Content-Type: application/json

[
    {
        "type": "text",
        "text": "Please fill the field."
    },
    {
        "type": "input",
        "id": "user_name_field"
    },
    {
        "type": "buttons",
        "ids": ["confirm_button"],
        "labels": ["Confirm"]
    }
]